spring:
  application:
    name: be4man-server

  jackson:
    time-zone: Asia/Seoul

  # .env import
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URL}
            scope:
              - read:user
              - user:email
              - repo
              - repo:status
              - repo_deployment
              - admin:repo_hook
              - repo:invite
            client-name: GitHub

# Server
server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 1209600000
  sign-expiration: 300000

# Frontend URL
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}


# Logging
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    sys.be4man.domains.taskmanagement.service: DEBUG



# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jenkins:
  url: ${JENKINS_URL}
  username: "be4man"
  password: ${JENKINS_PASSWORD}

gemini:
  api:
    key:
      ${GEMINI_API_KEY}

webhooks:
  github:
    secret: ${BE4MAN_WEBHOOK_SECRET}

github:
  token: ${GITHUB_TOKEN}
  apiBaseUrl: https://api.github.com